export const PopularCourseData = [
  {
    cardImg: "/img/popular-course/card-1.svg",
    video: "",
    title: "Basics of learning team management",
    profileImg: "/img/popular-course/profile-1.svg",
    name: "Jone Owel",
    designation: "IT Manager",
    number: 120,
    url: "",
    price: "120",
    quantity: "25",
  },
  {
    cardImg: "/img/popular-course/card-2.svg",
    video: "",
    title: "Learn basic database structure",
    profileImg: "/img/popular-course/profile-2.svg",
    name: "Roynaldo Jr",
    designation: "Data Science",
    number: 55,
    url: "",
    price: "180",
    quantity: "20",
  },
  {
    cardImg: "/img/popular-course/card-3.svg",
    video: "",
    title: "Create dynamic website with basic php",
    profileImg: "/img/popular-course/profile-3.svg",
    name: "Markus Low",
    designation: "Programer",
    number: 98,
    url: "",
    price: "135",
    quantity: "20",
  },
];
